#ifndef TOKALUENTODLL_GLOBAL_H
#define TOKALUENTODLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOKALUENTODLL_LIBRARY)
#  define TOKALUENTODLL_EXPORT Q_DECL_EXPORT
#else
#  define TOKALUENTODLL_EXPORT Q_DECL_IMPORT
#endif

#endif // TOKALUENTODLL_GLOBAL_H
