#ifndef TOKALUENTODLL2_GLOBAL_H
#define TOKALUENTODLL2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOKALUENTODLL2_LIBRARY)
#  define TOKALUENTODLL2_EXPORT Q_DECL_EXPORT
#else
#  define TOKALUENTODLL2_EXPORT Q_DECL_IMPORT
#endif

#endif // TOKALUENTODLL2_GLOBAL_H
